# Generated by Django 2.0.2 on 2018-02-26 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0004_auto_20180225_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Unit Name')),
                ('html_title', models.CharField(help_text='Unit with superscript tags. Eg. m3, m2...', max_length=30)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Measurement Units',
                'verbose_name': 'Measurement Unit',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.FloatField(blank=True, null=True, verbose_name='Recommeded Minimum Stock Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price Per Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supermarket.Unit', verbose_name='Measurement Unit'),
            preserve_default=False,
        ),
    ]
