# Generated by Django 2.0.2 on 2018-03-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0007_auto_20180228_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['on_sale', 'title', 'price']},
        ),
    ]
