# Generated by Django 2.0.2 on 2018-03-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0008_auto_20180303_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-on_sale', 'title', 'price']},
        ),
    ]
