# Generated by Django 2.0.2 on 2018-03-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0009_auto_20180303_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['featured', 'title'], 'verbose_name': 'Product Brand', 'verbose_name_plural': 'Product Brands'},
        ),
        migrations.AddField(
            model_name='brand',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
